module VerifyExamples.StaticArray.Index.FromInt1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray.Index exposing (..)
import StaticArray.Length as Length







spec1 : Test.Test
spec1 =
    Test.test "#fromInt: \n\n    fromInt Length.one 0\n    --> Just (fromLessThen Length.one 0)" <|
        \() ->
            Expect.equal
                (
                fromInt Length.one 0
                )
                (
                Just (fromLessThen Length.one 0)
                )