module VerifyExamples.StaticArray.Index.FromLessThen0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray.Index exposing (..)
import StaticArray.Index exposing (OnePlus,Two)
import StaticArray.Length as Length exposing (Length)



length : Length (OnePlus Two)
length =
    (Length.one |> Length.plus2)



spec0 : Test.Test
spec0 =
    Test.test "#fromLessThen: \n\n    fromLessThen length 3\n    --> last length --2" <|
        \() ->
            Expect.equal
                (
                fromLessThen length 3
                )
                (
                last length --2
                )