module VerifyExamples.StaticArray.Index.FromModBy0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray.Index exposing (..)
import StaticArray.Length as Length







spec0 : Test.Test
spec0 =
    Test.test "#fromModBy: \n\n    fromModBy (Length.one |> Length.plus2) 3\n    --> first --0" <|
        \() ->
            Expect.equal
                (
                fromModBy (Length.one |> Length.plus2) 3
                )
                (
                first --0
                )