module VerifyExamples.StaticArray.Index.Last0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray.Index exposing (..)
import StaticArray.Index as Index
import StaticArray.Length as Length







spec0 : Test.Test
spec0 =
    Test.test "#last: \n\n    Length.five\n    |> last\n    |> Index.toInt\n    --> 4" <|
        \() ->
            Expect.equal
                (
                Length.five
                |> last
                |> Index.toInt
                )
                (
                4
                )