module VerifyExamples.StaticArray.Length.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray.Length exposing (..)
import StaticArray







spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    StaticArray.singleton 42\n        |> StaticArray.push 7\n        |> StaticArray.length\n    --> two" <|
        \() ->
            Expect.equal
                (
                StaticArray.singleton 42
                    |> StaticArray.push 7
                    |> StaticArray.length
                )
                (
                two
                )