module VerifyExamples.StaticArray.Length.ToInt0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray.Length exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toInt: \n\n    four\n        |> toInt\n    --> 4" <|
        \() ->
            Expect.equal
                (
                four
                    |> toInt
                )
                (
                4
                )