module VerifyExamples.MARKDOWN.README.Test_0_5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray.Index as Index
import StaticArray.Length as Length
import StaticArray 







spec0 : Test.Test
spec0 =
    Test.test "Documentation VerifyExamples: \n\n    StaticArray.initialize Length.five (\\n -> n * n)\n      |> StaticArray.indexedMap (\\idx -> \\sqr -> (Index.toInt idx, sqr))\n      |> StaticArray.toList\n    --> [(0, 0), (1, 1), (2, 4), (3, 9), (4, 16)]" <|
        \() ->
            Expect.equal
                (
                StaticArray.initialize Length.five (\n -> n * n)
                  |> StaticArray.indexedMap (\idx -> \sqr -> (Index.toInt idx, sqr))
                  |> StaticArray.toList
                )
                (
                [(0, 0), (1, 1), (2, 4), (3, 9), (4, 16)]
                )