module VerifyExamples.MARKDOWN.README.Test_0_4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray exposing (StaticArray)
import StaticArray.Index as Index exposing (Two)
import StaticArray.Length as Length

type Food =
  Apples
  | Oranges

fromInt : Int -> Food
fromInt int =
  asArray
  |> StaticArray.get (int |> Index.fromModBy Length.two)
toInt : Food -> Int
toInt food =
  case food of
    Apples -> 0
    Oranges -> 1
asArray : StaticArray Two Food
asArray =
  StaticArray.fromList Length.two Apples [Oranges]



spec0 : Test.Test
spec0 =
    Test.test "Documentation VerifyExamples: \n\n    Apples\n    |> toInt\n    |> fromInt\n    --> Apples" <|
        \() ->
            Expect.equal
                (
                Apples
                |> toInt
                |> fromInt
                )
                (
                Apples
                )