module VerifyExamples.MARKDOWN.README.Test_0_0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray
import StaticArray.Length as Length







spec0 : Test.Test
spec0 =
    Test.test "Documentation VerifyExamples: \n\n      (0,[1,2,3,4,5])\n      |> StaticArray.fromList (Length.five |> Length.plus1)\n      |> StaticArray.toList\n    --> [0,1,2,3,4,5]" <|
        \() ->
            Expect.equal
                (
                  (0,[1,2,3,4,5])
                  |> StaticArray.fromList (Length.five |> Length.plus1)
                  |> StaticArray.toList
                )
                (
                [0,1,2,3,4,5]
                )