module VerifyExamples.StaticArray.FromList1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray exposing (..)
import StaticArray.Length as Length







spec1 : Test.Test
spec1 =
    Test.test "#fromList: \n\n    fromList Length.five (0,[])\n        |> toList\n    --> [0,0,0,0,0]" <|
        \() ->
            Expect.equal
                (
                fromList Length.five (0,[])
                    |> toList
                )
                (
                [0,0,0,0,0]
                )