module VerifyExamples.StaticArray.FromList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray exposing (..)
import StaticArray.Length as Length
import Array







spec0 : Test.Test
spec0 =
    Test.test "#fromList: \n\n    fromList Length.five 0 []\n        |> toArray\n        |> Array.toList\n    --> [0,0,0,0,0]" <|
        \() ->
            Expect.equal
                (
                fromList Length.five 0 []
                    |> toArray
                    |> Array.toList
                )
                (
                [0,0,0,0,0]
                )