module VerifyExamples.StaticArray.Initialize0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray exposing (..)
import StaticArray.Length as Length







spec0 : Test.Test
spec0 =
    Test.test "#initialize: \n\n    initialize Length.five (\\i -> i*i)\n    --> fromList Length.five 0 [1,4,9,16]" <|
        \() ->
            Expect.equal
                (
                initialize Length.five (\i -> i*i)
                )
                (
                fromList Length.five 0 [1,4,9,16]
                )