module VerifyExamples.StaticArray.ToRecord0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import StaticArray exposing (..)
import StaticArray.Index exposing (Five,OnePlus)
import StaticArray.Length as Length



array : StaticArray (OnePlus Five) Int
array =
    fromList (Length.five |> Length.plus1 ) 0
        [1,2,3,4,5]



spec0 : Test.Test
spec0 =
    Test.test "#toRecord: \n\n    array |> toRecord |> fromRecord\n    --> array" <|
        \() ->
            Expect.equal
                (
                array |> toRecord |> fromRecord
                )
                (
                array
                )